plugins {
    id 'application'
}

group = 'com.restonic4.bloom'
version = '0.1'
project.ext.lwjglVersion = "3.4.3"

static def detectHostNatives() {
    def os = System.getProperty("os.name").toLowerCase()
    def arch = System.getProperty("os.arch").toLowerCase()

    if (os.contains("linux")) {
        if (arch.startsWith("aarch64") || arch.startsWith("arm64")) {
            return "natives-linux-arm64"
        }
        return "natives-linux"
    }

    if (os.contains("freebsd")) {
        return "natives-freebsd"
    }

    if (os.contains("mac")) {
        if (arch.startsWith("aarch64") || arch.startsWith("arm64")) {
            return "natives-macos-arm64"
        }
        return "natives-macos"
    }

    if (os.contains("windows")) {
        if (arch.startsWith("aarch64") || arch.startsWith("arm64")) {
            return "natives-windows-arm64"
        }
        return "natives-windows"
    }

    throw new GradleException("Unsupported host OS: ${os}")
}

def lwjglNatives = providers.gradleProperty("lwjglNatives").getOrElse(detectHostNatives())
def targetPlatform = providers.gradleProperty("targetPlatform").getOrElse("local")

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-openal"
    implementation "org.lwjgl:lwjgl-opengl"
    implementation "org.lwjgl:lwjgl-assimp"

    runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-glfw::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-openal::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-opengl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-assimp::$lwjglNatives"

    implementation("org.joml:joml:1.10.8")

    implementation 'com.restonic4.bloom:events:1.0.0'
    annotationProcessor("com.restonic4.bloom:events:1.0.0")
}

application {
    mainClass = 'com.restonic4.unlock.Unlock'
}

tasks.named("distZip", Zip) {
    archiveFileName = "${project.name}-${project.version}-${targetPlatform}.zip"
}